---
title: "Reliability functions"
author: "Sebastiaan de Klerk"
date: "22-8-2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/s.dklerk/OneDrive - eX plain/eXplain/
                     Innovatie & Onderzoek/Projectleiding/R projecten/Reliability
                     /reliability_analysis")
```

```{r}
lopezAlpha <- function(binary_response_matrix) {
  
  # Lopez : Correction on Cronbach's alpha based on inter item correlations
  #
  # input: binary.response.matrix : Binary responses to all items.
  
  #Calculate inter item correlation matrix
  inter_item_cor      <- cor(binary_response_matrix, method = "pearson", 
                             use = "pairwise.complete.obs")
  
  # Calculate lower triangle of inter item correlation matrix
  inter_item_cor_tri  <- inter_item_cor[lower.tri(inter_item_cor)]
  
  # Caclulate mean inter item correlation
  mean_inter_item_cor <- mean(inter_item_cor_tri, na.rm = T)
  
  # Calculate number of items in item bank
  number_of_items = dim(binary_response_matrix)[2]
  
  # Calculate Lopez alpha
  Lopez_alpha         <- (number_of_items * mean_inter_item_cor) / 
                         (1+(number_of_items - 1)*mean_inter_item_cor)
  
  #Return Lopez alpha reliability estimate
  return(list("The Lopez alpha reliability estimate is:", round(Lopez_alpha, 2)))
}
```

```{r}
sdTest <- function(binary_response_matrix) {
  
  # sdTest : Standard deviation of total test.
  #          Calculated using point biserial correlation.
  #
  # input: binary.response.matrix : Binary responses to all items.
  
  # Load ltm package
  library(ltm)
  
  # Calculate proportion correct item
  proportions_correct <- apply(binary_response_matrix, 2, mean, na.rm = T)
  
  # Calculate total sum score per test taker
  sum_scores          <- apply(binary_response_matrix, 1, sum,  na.rm = T)
  
  # Create empty vector to store item total correlations
  r_it                <- vector()
  
  # Calculate number of items in response matrix
  number_of_items     <- dim(binary_response_matrix)[2]
  
  # Calculate point biserial correlation per item with total sum score
  for(i in 1:number_of_items) { 
    
    r_it[i]           <-  biserial.cor(sum_scores, binary_response_matrix[,i], 
                                       level=2, use = "complete.obs") 
  }
  
  # Calculate standard deviation of the test
  SD_test             <- sum(r_it*sqrt(proportions_correct*(1-proportions_correct)), na.rm = T)
  
  # Return standard deviation of the test
  return(list("The standard deviation of the test is:", round(SD_test, 2)))  
}
```

```{r}
kr20 <- function(binary_response_matrix) {
  
  # kr20: reliability estimate
  #
  # input: binary.response.matrix : Binary responses to all items.
  
  # Calculate number of items in response matrix
  number_of_items      <- dim(binary_response_matrix)[2]
  
  # Calculate probability vector of proporitons correct per item
  proportions_correct  <- apply(binary_response_matrix, 2, mean, na.rm = T)
  
  # Calculate total sum score per test taker
  sum_scores           <- apply(binary_response_matrix, 1, sum,  na.rm = T)
  
  # Create empty vector to store item total correlations
  r_it                 <- vector()
  
  # Calculate point biserial correlation per item with total sum score
  for(i in 1:number_of_items) { 
    
    r_it[i]            <-  biserial.cor(sum_scores, binary_response_matrix[,i], 
                                       level=1, use = "complete.obs")
  }
  
  # Calculate standard deviation of the test
  SD_test              <- sum(r_it*sqrt(proportions_correct*(1-
                              proportions_correct)), na.rm = T)
  
  # Calculate kr20
  kr20                 <- (number_of_items/(number_of_items-1))*(1-(sum
                          (proportions_correct*(1-proportions_correct))/SD_test^2))
  
  # Return kr20 reliability estimate
  return(list("The kr20 reliability estimate is:", round(kr20, 2)))
}
```

```{r}
sbCorrection <- function(binary_response_matrix, cronbach_alpha) {
  
  # SpearmanBrownPredictionFormula : Mean reliability on extended or 
  #                                   shortened test
  #
  # input:     kr20/lopez : Pre determined reliability
  
  # Calcuatle number of items in response matrix
  number_of_items       <- dim(binary_response_matrix)[2]
  
  # Calculate number of items in test
  number_of_items_test  <- length(binary_response_matrix[1,][!is.na
                                 (binary_response_matrix[1,])])
  
  # Caclulate k factor
  k                     <- number_of_items_test/number_of_items
  
  # Calculate SB corrected alpha
  mean_scaled_alpha     <- (k*cronbach_alpha)/(1+(k-1)*cronbach_alpha)
  
  # Return SB corrected kr20 / lopez
  return(list("The SB corrected reliability estimate is:", mean_scaled_alpha))
}
```

```{r}
ritValues <- function(binary_response_matrix) {
  
  # Rit:          Rit values for all items in item bank
  #
  # input:        binary_response_matrix: Binary responses to all items
  
  # Calculate total sum score per test taker
  sum_scores  <- apply(binary_response_matrix, 1, sum,  na.rm = T)
  
  # Create empty vector to store item total correlations
  r_it <- vector()
  
  # Calculate number of items in response matrix
  number_of_items <- dim(binary_response_matrix)[2]
  
  # Calculate point biserial correlation per item with total sum score
  for(i in 1:number_of_items) { 
    
    r_it[i] <-  biserial.cor(sum_scores, binary_response_matrix[,i], level=2, 
                             use = "complete.obs")  
  }
  
  #Return Rit values for all items in item bank
  return(r_it)
}
```

```{r}
reliabilityPat <- function(binary_response_matrix){
  
  # reliabilityPat  : Reliability as calculated in PAT
  #
  # input           : binary_response_matrix     : response matrix with binaries
  
  # Calculate number of items in a test 
  n           <- length(binary_response_matrix[1,][!is.na(binary_response_matrix[1,])])
  
  # Calculate number of items in response matrix
  number_of_items <- dim(binary_response_matrix)[2]
  
  # Calculate sum score per test taker
  sum_scores  <- apply(binary_response_matrix, 1, sum,  na.rm = T)
  
  # Create empty vector to store rit values
  r_it <- vector()
  
  # Store rit values in empty vector
  for(i in 1:number_of_items) { 
    
  r_it[i] <-  biserial.cor(sum_scores, data_hw[,i], level=2, use = "complete.obs")  
  }
  
  # Calculate mean rit value
  mean_rit <- round(mean(r_it, na.rm = T), 2)
  
  # Calculate reliability as in PAT
  reliability_pat <- round(n/(n-1)*(1-(1/(n*((mean_rit)^2)))), 2)
  
  #return reliability as in PAT
  return(list("The number of items in a test is:", n, "The mean Rit is:", 
              mean_rit, "The reliability is:", reliability_pat))
}
```

